### ISSUE TITLE
Build fails due to undefined references in yara when building yaracpp

### ISSUE THREAD

**Issue by Janrupf** [avast-tl/retdec#252]
Hello,
I'm trying to build on Linux Mint 18.3 and just followed the build instructions.
CMake is running successfull (using local version because distribution own is to old).
CMake version: 3.11.0-rc3

Anyway, that whats the build log tells me:

yaracpp-project-build-err.log
```
make[6]: Warnung: -jN in „make“-Verarbeitungszweig erzwungen: 
Jobserver-Modus nicht verfügbar.
yarac.o: In function `define_external_variables':
yarac.c:(.text+0x170): undefined reference to `yr_compiler_define_boolean_variable'
yarac.c:(.text+0x1b1): undefined reference to `yr_compiler_define_integer_variable'
yarac.c:(.text+0x1ca): undefined reference to `yr_compiler_define_string_variable'
yarac.o: In function `main':
yarac.c:(.text.startup+0x64): undefined reference to `yr_initialize'
yarac.c:(.text.startup+0x80): undefined reference to `yr_compiler_destroy'
yarac.c:(.text.startup+0x8f): undefined reference to `yr_rules_destroy'
yarac.c:(.text.startup+0x94): undefined reference to `yr_finalize'
yarac.c:(.text.startup+0x162): undefined reference to `yr_compiler_create'
yarac.c:(.text.startup+0x1a2): undefined reference to `yr_compiler_set_callback'
yarac.c:(.text.startup+0x1e1): undefined reference to `yr_compiler_add_file'
yarac.c:(.text.startup+0x25b): undefined reference to `yr_compiler_get_rules'
yarac.c:(.text.startup+0x270): undefined reference to `yr_rules_save'
collect2: error: ld returned 1 exit status
make[7]: *** [yarac] Fehler 1
make[7]: *** Auf noch nicht beendete Prozesse wird gewartet …
yara.o: In function `scanning_thread':
yara.c:(.text+0x85e): undefined reference to `yr_rules_scan_file'
yara.c:(.text+0x90d): undefined reference to `yr_finalize_thread'
yara.o: In function `handle_message':
yara.c:(.text+0xb0e): undefined reference to `yr_get_tidx'
yara.o: In function `callback':
yara.c:(.text+0xfa5): undefined reference to `yr_object_print_data'
yara.o: In function `define_external_variables':
yara.c:(.text+0x11bb): undefined reference to `yr_rules_define_float_variable'
yara.c:(.text+0x11e2): undefined reference to `yr_compiler_define_float_variable'
yara.c:(.text+0x12bb): undefined reference to `yr_rules_define_boolean_variable'
yara.c:(.text+0x12ef): undefined reference to `yr_compiler_define_boolean_variable'
yara.c:(.text+0x1337): undefined reference to `yr_rules_define_integer_variable'
yara.c:(.text+0x136a): undefined reference to `yr_compiler_define_integer_variable'
yara.c:(.text+0x13dd): undefined reference to `yr_rules_define_string_variable'
yara.c:(.text+0x1401): undefined reference to `yr_compiler_define_string_variable'
yara.o: In function `load_modules_data':
yara.c:(.text+0x147a): undefined reference to `yr_filemap_map'
yara.o: In function `unload_modules_data':
yara.c:(.text+0x1541): undefined reference to `yr_filemap_unmap'
yara.o: In function `main':
yara.c:(.text.startup+0x151): undefined reference to `yr_compiler_destroy'
yara.c:(.text.startup+0x160): undefined reference to `yr_rules_destroy'
yara.c:(.text.startup+0x165): undefined reference to `yr_finalize'
yara.c:(.text.startup+0x1a8): undefined reference to `yr_initialize'
yara.c:(.text.startup+0x1ca): undefined reference to `yr_set_configuration'
yara.c:(.text.startup+0x1d8): undefined reference to `yr_rules_load'
yara.c:(.text.startup+0x24e): undefined reference to `yr_rules_scan_proc'
yara.c:(.text.startup+0x295): undefined reference to `yr_compiler_create'
yara.c:(.text.startup+0x2d1): undefined reference to `yr_compiler_set_callback'
yara.c:(.text.startup+0x2fe): undefined reference to `yr_compiler_add_file'
yara.c:(.text.startup+0x338): undefined reference to `yr_compiler_get_rules'
yara.c:(.text.startup+0x345): undefined reference to `yr_compiler_destroy'
yara.c:(.text.startup+0x3c5): undefined reference to `yr_rules_scan_file'
collect2: error: ld returned 1 exit status
make[7]: *** [yara] Fehler 1
make[6]: *** [all-recursive] Fehler 1
make[5]: *** [deps/yara/src/yara-stamp/yara-build] Fehler 2
make[4]: *** [deps/CMakeFiles/yara.dir/all] Fehler 2
make[3]: *** [all] Fehler 2
```

yaracpp-project-build-out.log
```
[  7%] Performing build step for 'yara'
Making all in libyara
libtool: link: gcc -std=gnu99 -Wall -I./libyara/include -O3 -pthread -o yarac args.o yarac.o  libyara/.libs/libyara.a -lm -pthread
Makefile:783: die Regel für Ziel „yarac“ scheiterte
libtool: link: gcc -std=gnu99 -Wall -I./libyara/include -O3 -pthread -o yara args.o threading.o yara.o  libyara/.libs/libyara.a -lm -pthread
Makefile:779: die Regel für Ziel „yara“ scheiterte
Makefile:886: die Regel für Ziel „all-recursive“ scheiterte
deps/CMakeFiles/yara.dir/build.make:115: die Regel für Ziel „deps/yara/src/yara-stamp/yara-build“ scheiterte
CMakeFiles/Makefile2:85: die Regel für Ziel „deps/CMakeFiles/yara.dir/all“ scheiterte
Makefile:83: die Regel für Ziel „all“ scheiterte
```

System is german btw

**Comment by s3rvac** [comment]
Hi. I have successfully managed to build RetDec on Linux Mint 18.2 (CMake 3.11.0-rc3) inside Docker. So, I am not sure why the build does not work on your system...

**Comment by s3rvac** [comment]
I suggest the following approach. @Janrupf: First, try to build `yaracpp` alone:
```
git clone https://github.com/avast-tl/yaracpp.git
cd yaracpp
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make |& tee yaracpp-make-log.txt
```
If this fails, attach/send us `yaracpp-make-log.txt` and try building `yara` alone:
```
git clone https://github.com/avast-tl/yara/ -b retdec
cd yara
./bootstrap.sh
./configure --disable-shared --without-crypto
make |& tee yara-make-log.txt
```
If this fails, also attach/send us `yara-make-log.txt`.

**Comment by Janrupf** [comment]
Ok, so same error with yaracpp alone:
[yaracpp-make-log.txt](https://github.com/avast-tl/retdec/files/1860113/yaracpp-make-log.txt)

And well, same with yara:
[yara-make-log.txt](https://github.com/avast-tl/retdec/files/1860117/yara-make-log.txt)

**Comment by s3rvac** [comment]
Thank you. So, now we know that the problem is in the build of `yara`. I believe that the reason why it fails to find the references inside `libyara.a` is indicated by the following line:
```
warning: ranlib: warning for library: .libs/libyara.a the table of contents is empty (no object file members in the library define global symbols)
```
However, I am not sure what is the underlying cause of the warning.

Could you now please perform the following two steps?
1. Run these four commands and give us their output:
    ```
    gcc --version
    ar --version
    ranlib --version
    libtool --version
    ```
2. Try the `yara` build on the official repository (in RetDec and related tools, we use our custom version of `yara`):
    ```
    git clone https://github.com/VirusTotal/yara
    cd yara
    ./bootstrap.sh
    ./configure --disable-shared --without-crypto |& tee yara-configure-log.txt
    make |& tee yara-make-log.txt
    ```
    Then, attach the `yara-configure-log.txt` and `yara-make-log.txt` files.

**Comment by s3rvac** [comment]
Hi @Janrupf. Were you able to try the `yara` build from the official repository? See my comment above (point 2). Also, please give us the output from the four commands above (point 1).

**Comment by Janrupf** [comment]
Ok, so sorry that it took so long :)

Here are the outputs:
gcc --version
```
gcc (Ubuntu 5.5.0-11ubuntu1~16.04.york0.1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

ar, libtool and ranlib do not support the option --version,

Yara build logs:
[yara-configure-log.txt](https://github.com/avast-tl/retdec/files/1947536/yara-configure-log.txt)
[yara-make-log.txt](https://github.com/avast-tl/retdec/files/1947537/yara-make-log.txt)

**Comment by s3rvac** [comment]
Thank you. As can be seen from the `yara-make-log.txt` log, the build fails also with a vanilla upstream version of Yara, so the problem is in there and not in the decompiler. You will have to submit an issue [there](https://github.com/VirusTotal/yara/issues) as this is a third-party library that RetDec uses. I am sorry we were not able to help you.

> ar, libtool and ranlib do not support the option --version

This is strange. I believe that you are using non-standard versions of these tools, which is probably why the Yara build fails. You should be using the GNU versions, which support the `--version` parameter. I would start here. Could you please run the following command?
```
dpkg -l | grep "ii  \(binutils\|libtool\)"
```
It should produce output similar to this:
```
ii  binutils      2.26.1-1ubuntu1~16.04.6       amd64    GNU assembler, linker and binary utilities
ii  libtool       2.4.6-0.1                     all      Generic library support script
```

**Comment by Janrupf** [comment]
Thank you for your support. I just had the same issue with 3 other cpp projects. I think I broke my system core or something like this. Anyway, the problem is clearly on my side.
