### ISSUE TITLE
Linux build fails with "fatal error: llvm/ADT/Triple.h: No such file or directory"

### ISSUE THREAD

**Issue by AlbrechtL** [avast-tl/retdec#62]
Unfortunately the build failed on my Ubuntu 16.04 x64 with the following output
   ```
[ 75%] Building CXX object src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/bin2llvmir.cpp.o
/home/albrecht/src/retdec/src/bin2llvmirtool/bin2llvmir.cpp:18:29: fatal error: llvm/ADT/Triple.h: No such file or directory
compilation terminated.
src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/build.make:62: recipe for target 'src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/bin2llvmir.cpp.o' failed
make[2]: *** [src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/bin2llvmir.cpp.o] Error 1
CMakeFiles/Makefile2:6082: recipe for target 'src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/all' failed
make[1]: *** [src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
   ```
Any hint how to solve it?

**Comment by gwirth79** [comment]
The same thing happens on Fedora 27. The failure is:

`Scanning dependencies of target bin2llvmirtool
[ 75%] Building CXX object src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/bin2llvmir.cpp.o
/home/gus/src/RetDec/retdec/src/bin2llvmirtool/bin2llvmir.cpp:18:10: fatal error: llvm/ADT/Triple.h: No such file or directory
 #include <llvm/ADT/Triple.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/build.make:63: src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/bin2llvmir.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6083: src/bin2llvmirtool/CMakeFiles/bin2llvmirtool.dir/all] Error 2
make: *** [Makefile:152: all] Error 2`

However, the file exists in several places:

`[gus@falcon retdec]$ find . -name Triple.h
./deps/capstone2llvmir/deps/keystone/llvm/include/llvm/ADT/Triple.h
./deps/capstone2llvmir/deps/llvm/src/include/llvm/ADT/Triple.h
./deps/fileformat/deps/llvm/src/include/llvm/ADT/Triple.h
./deps/llvm/src/include/llvm/ADT/Triple.h
./deps/fnc-patterns/deps/fileformat/deps/llvm/src/include/llvm/ADT/Triple.h`

Apparently there is a path problem somewhere.

On a totally unrelated note, wtf is wrong with the markup system where it doesn't honor end of line in code samples?

**Comment by Tremolo4** [comment]
Can confirm, I guess this was broken in 1e469383e15f9ea8dabea741a51037d72899b1d9

Building 7d67338abf1e6b2c41ea510d6f23411e33417d21 works for me.

**Comment by s3rvac** [comment]
Thank you for the report. I can confirm that the Linux build currently fails. It seems to be caused by the changes in the newly added support for build on macOS. We will fix this ASAP.

**Comment by s3rvac** [comment]
Fixed in a8a24aa64c0c34cd3a64141afffb30ae4b8b11e4.

**Comment by AlbrechtL** [comment]
Works now! Thanks for fixing it so fast!
